--- 
- name: install tomcat on redhat
  become: yes
  hosts: all
  vars:
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
    tomcat_major_version: 10
    tomcat_specific_version: 10.1.14
  tasks:
    - name: install java
      ansible.builtin.dnf:
        name: "openjdk-{{ java_version }}-jdk"
        state: present
        update_cache: yes
    - name: add tomcat user and give permissions
      ansible.builtin.user:
        name: "{{ username }}"
        shell: "{{ shell }}"
        group: "{{ groupname }}"
        create_home: true
        home: "{{ homedir }}"
    - name: Ensure group "tomcat" exists
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present
    - name: download the tomcat file
      ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major-version }}/v{{ tomcat_specific_version }}/bin/apache-tomcat-{{ tomcat_specific_version }}.tar.gz
      dest: /tmp/apache-tomcat-{{ tomcat_specific_version }}.tar.gz
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_specific_version }}.tar.gz
        dest: "{{ homedir }}"
    - name: give symbalik link
      ansible.builtin.file:
        src: "{{ homedir }}/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
        dest: "{{ homedir }}/latest"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        state: link
        recurse: yes
    - name: give the file permissions 
      ansible.builtin.file:
      path: "{{ homedir }}"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: '0755'
    - name: get all the shell files
      ansible.builtin.command: sudo sh -c 'ls /opt/tomcat/latest/bin/*.sh'
      register: shell_files
    - name: print the value
      ansible.builtin.debug:
        var: shell_files
    - name: add execute permission
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: "0751"
      loop: "{{ shell_files.stdout_lines }}"