---
- name: tomcat server installation
  become: yes
  hosts: all
  tasks: 
    - name: installing tomcat service
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        home: /opt/tomcat
        state: present
    - name: install java
      ansible.builtin.apt:
        name: default-jdk
        state: present
        update_cache: yes
    - name: dowload tomcat serverin tar file
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
        dest: /tmp/apache-tomcat-10.1.13.tar.gz
      
    - name: untar the downloaded package
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.1.13.tar.gz
        dest: /opt/tomcat

    - name: Add the user 'tomcat' 
      ansible.builtin.user:
        name: tomcat

    - name: change file ownership  permissions
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
    - name: change file ownership and group permissions
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
    - name: to create a service file 
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/tomcat.service
    - name: restart the daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: systemctl start the service
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: to check the status
      ansible.builtin.command: systemctl status tomcat
      register: myoutput
  
    
