---
- name: install apache and php 
  become: yes
  hosts: webserver
  tasks: 
    - name: install apache and php
      ansible.builtin.apt:
        name: 
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes
      when: ansible_facts["os_family"] == "Debian"
    
    - name: install php page in redhat machine
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-cli
          - php-common
          - php-gd
          - php-mysqlnd
          - php-pdo
        state: present
        update_cache: yes
      when: ansible_facts["os_family"] == "RedHat"

    - name: create a info.php page
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php

    - name: run the httpd service
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_facts["os_family"] == "ReHhat"
    

